Titanium.App.DIARY = {
	SELECTEDYEAR: '2010',
	SELECTEDMONTH: '',
	DATABASENAME: 'mydiary',
	TABLENAME: 'MYPAGES'
};

var db = Titanium.Database.open(Titanium.App.DIARY.DATABASENAME);
db.execute( 'CREATE TABLE IF NOT EXISTS ' + Titanium.App.DIARY.TABLENAME + ' (PGID INTEGER PRIMARY KEY, PGDAY INTEGER , PGMONTH INTEGER, NOTES TEXT)' );
