<?php


$FILESERVER_CONFIGURATION = array(
	'BASEURL' => 'http://192.168.1.10/fs/' , // $FILESERVER_CONFIGURATION['BASEURL']
	'MYAPPS' => array(
		'MYAPP1' => 'MYAPP1_KEY', // APPNAME => APPKEY == $FILESERVER_CONFIGURATION['MYAPPS']['MYAPP1'] , 
		'MYAPP2' => 'MYAPP2_KEY', // APPNAME => APPKEY
	)
);


?>